var studentQuote = {
   "ali" : "You're almost always wrong about your user",
   "amnon" : "Those who never fail are those who never try.",
   "ben" : "Only people in glass houses should throw stones, provided that they are trapped.",
   "chibuzo" : "My last name is two letters away from being a palindrome",
   "christy" : "If something bad happens, something good will come of it.",
   "daisy" : "Life between natural and digital",
   "elaine" : "Do one thing every day that scares you.",
   "gustavo" : "Lifelong learner and tinkerer. I Love to combine tech and art in any way that I can.",
   "julien" : "Well-rounded, full-stack developer seeking opportunities in Waterloo.",
   "laura" : "I love mathematics, making beautiful websites, and climbing rocks.",
   "lauren" : "Create something no one has seen before using something no one has tried.",
   "linus" : "Talk is cheap. Show me the code",
   "lulu" : "Shoot for the sky, because even if you miss, you'll still land among the stars.",
   "madzia" : "Fighting evil by moonlight, pushing pixels by daylight",
   "meagan" : "It’s Puzzle Time!",
   "mengsi" : "Simplicity is the ultimate sophistication. — Leonardo da Vinci",
   "natalia" : "Coffee, Create, Sleep, Repeat",
   "natasha" : "Product Designer with qualifications in education and commerce",
   "nick" : "Simplicity is the ultimate sophistication.",
   "nicole" : "Work until your IDOLS become your RIVALS",
   "paul" : "I create the vision that influences the process of the user-centric environment.",
   "priyanka" : "A digital enthusiast who enjoys being a part of a creative culture that innovates new designs.",
   "rachel" : "I'm a UI/UX designer, sensitive observer and coffee addict living in Canada.",
   "vladan" : "Programmed to prevent global genocide of imagination",
   "ziqin" : "Never Say Die!",
};

var studentTitle = {
   "ali" : "UX, Front-End Developer & Interactive Designer",
   "amnon" : "UI/UX, Front-End Developer & Interactive Designer",
   "ben" : "Multimedia & Front-End Developer",
   "chibuzo" : "Front-End Developer",
   "christy" : "UI/UX, Interactive & Graphic Designer",
   "daisy" : "UX/UI Designer, Web designer/developer",
   "elaine" : "UI/UX, Front-End Developer & Interactive Designer",
   "gustavo" : "UX, Front-End Developer, Interactive & Graphic Designer",
   "julien" : "Full-Stack Developer",
   "laura" : "Front-End & Back-End Developer",
   "lauren" : "Project Manager & Interactive Designer/Developer",
   "linus" : "Front-End Developer",
   "lulu" : "UI/UX, Front-End Developer & Graphic Designer",
   "madzia" : "UI/UX Designer",
   "meagan" : "Front-End Developer",
   "mengsi" : "UI/UX Specialist",
   "natalia" : "UI/UX Designer",
   "natasha" : "Marketing/Social Media Specialist",
   "nick" : "UI/UX, Interactive & Graphic Designer",
   "nicole" : "UI/UX & Front-End Developer",
   "paul" : "UI/UX Specialist",
   "priyanka" : "UI/UX, Front-End & Interactive Developer",
   "rachel" : "UI/UX, Front-End Developer & Interactive Designer",
   "vladan" : "UI/UX & Interactive Designer",
   "ziqin" : "UI/UX, Front-End Developer, Interactive & Graphic Designer",
};

var studentName = {
   "ali" : "Humayun (Ali) Ahmed",
   "amnon" : "Amnon Skladman",
   "ben" : "Ben Leger",
   "chibuzo" : "Chibuzo Uguru",
   "christy" : "Sitong Wang",
   "daisy" : "Daisy Shen",
   "elaine" : "Elaine Tran",
   "gustavo" : "Gustavo Costa",
   "julien" : "Julien Lapointe",
   "laura" : "Laura Warr",
   "lauren" : "Lauren Harvey",
   "linus" : "Linus Wang",
   "lulu" : "Lulu Kang",
   "madzia" : "Madzia McCutcheon",
   "meagan" : "Meagan Peat",
   "mengsi" : "Mengsi Gong",
   "natalia" : "Natalia Camarena",
   "natasha" : "Natasha Sidi",
   "nick" : "Nico Abais",
   "nicole" : "Nicole Yu",
   "paul" : "Paul Spry",
   "priyanka" : "Priyanka Panjwani",
   "rachel" : "Rachel Han",
   "vladan" : "Vladan Mutabdzija",
   "ziqin" : "Ziqin Gao",
};

var studentLinkedin = {
   "ali" : "https://www.linkedin.com/in/humayuna/",
   "amnon" : "https://www.linkedin.com/in/amnon-skladman-67b66493/",
   "ben" : "https://www.linkedin.com/in/benleger/",
   "chibuzo" : "https://www.linkedin.com/in/chibuzouguru/",
   "christy" : "https://www.linkedin.com/in/sitong-wang-297262127/",
   "daisy" : "https://www.linkedin.com/in/daisy90/",
   "elaine" : "https://www.linkedin.com/in/elaine-tran/",
   "gustavo" : "https://www.linkedin.com/in/gustavotcosta/",
   "julien" : "https://www.linkedin.com/in/julienlapointe",
   "laura" : "http://www.linkedin.com/in/laura-warr-02009275/",
   "lauren" : "https://www.linkedin.com/in/lauren-e-harvey/",
   "linus" : "https://www.linkedin.com/in/linus0520/",
   "lulu" : "https://www.linkedin.com/in/lulukang/",
   "madzia" : "https://www.linkedin.com/in/madziamcc/",
   "meagan" : "https://www.linkedin.com/in/meaganpeat/",
   "mengsi" : "https://www.linkedin.com/in/mengsigong/",
   "natalia" : "https://www.linkedin.com/in/natalia-camarena-6a00245b/",
   "natasha" : "https://www.linkedin.com/in/natashasidi",
   "nick" : "https://ca.linkedin.com/in/nicoabais",
   "nicole" : "https://www.linkedin.com/in/thenicoleyu/",
   "paul" : "https://twitter.com/pauljspry",
   "priyanka" : "https://www.linkedin.com/in/priyankapanjwani/",
   "rachel" : "https://www.linkedin.com/in/rachelhanhyewon/",
   "vladan" : "https://www.linkedin.com/in/vladanmutabdzija/",
   "ziqin" : "https://www.linkedin.com/in/ziqin-gao/",
};

var studentGithub = {
   "ali" : "https://github.com/ali2k4",
   "amnon" : "https://github.com/AmnonSkladman",
   "ben" : "https://github.com/Benjamin1771",
   "chibuzo" : "https://github.com/CUguru",
   "christy" : "https://github.com/sitongwang",
   "daisy" : "https://github.com/DAISYshen",
   "elaine" : "https://github.com/elainecookiee",
   "gustavo" : "https://github.com/gustavo-costa",
   "julien" : "https://github.com/julienlapointe",
   "laura" : "https://github.com/lauraawarr",
   "lauren" : "https://github.com/laurenhrv",
   "linus" : "https://github.com/Linus0520",
   "lulu" : "https://github.com/lulunak",
   "madzia" : "https://github.com/madziamcc",
   "meagan" : "https://github.com/MeaganPeat",
   "mengsi" : "https://github.com/mengsigong",
   "natalia" : "https://github.com/camarenn",
   "natasha" : "https://github.com/nsidi",
   "nick" : "",
   "nicole" : "https://github.com/thenicoleyu",
   "paul" : "https://github.com/PaulSpry",
   "priyanka" : "https://github.com/priancadesign",
   "rachel" : "https://github.com/hw0292",
   "vladan" : "https://github.com/vladannm",
   "ziqin" : "https://github.com/ZiqinGao",
};

var studentTwitter = {
   "ali" : "https://twitter.com/AliAhmed151989",
   "amnon" : "https://twitter.com/plaidygami",
   "ben" : "https://twitter.com/BenLeger7",
   "chibuzo" : "https://twitter.com/C_Uguru",
   "christy" : "https://twitter.com/ChristyWang1124",
   "daisy" : "https://twitter.com/DAIZI90",
   "elaine" : "https://twitter.com/elainecookiee",
   "gustavo" : "",
   "julien" : "https://twitter.com/julienlapointe",
   "laura" : "https://twitter.com/meet_laurawarr",
   "lauren" : "https://twitter.com/luarne",
   "linus" : "https://twitter.com/Linus_0520",
   "lulu" : "https://twitter.com/lulu_k423",
   "madzia" : "https://twitter.com/madziamcc",
   "meagan" : "https://twitter.com/MeaganPeat",
   "mengsi" : "",
   "natalia" : "https://twitter.com/n_camarenas",
   "natasha" : "https://mobile.twitter.com/natashasidi",
   "nick" : "https://twitter.com/ballsofnick",
   "nicole" : "https://twitter.com/thenicoleyu",
   "paul" : "https://twitter.com/pauljspry",
   "priyanka" : "https://twitter.com/PriancaPan",
   "rachel" : "https://twitter.com/hw02921",
   "vladan" : "https://twitter.com/vladann",
   "ziqin" : "https://twitter.com/ziqingao",
}

var studentPortfolio = {
   "ali" : "http://uxdev.ca/",
   "amnon" : "http://www.amnon.rocks/",
   "ben" : "http://legerbe.dev.fast.sheridanc.on.ca/Portfolio/",
   "chibuzo" : "http://www.chibuzouguru.com/",
   "christy" : "http://www.thesitongwang.com/",
   "daisy" : "http://www.daizistudio.com/",
   "elaine" : "http://elainetran.me/",
   "gustavo" : "https://gustavocosta.net/",
   "julien" : "http://www.julienlapointe.com/",
   "laura" : "http://www.laurawarr.ca/",
   "lauren" : "http://harveyla.dev.fast.sheridanc.on.ca/portfolio/",
   "linus" : "http://www.linuswang.com/",
   "lulu" : "http://www.lulukang.ca/",
   "madzia" : "http://www.madziamcc.com/",
   "meagan" : "http://www.meaganpeat.ca/",
   "mengsi" : "http://www.mengsigong.com/",
   "natalia" : "http://www.ncamarena.com/",
   "natasha" : "http://www.natashasidi.com/",
   "nick" : "http://www.heynick.ca/",
   "nicole" : "http://www.thenicoleyu.com/",
   "paul" : "http://www.pauljspry.com/",
   "priyanka" : "http://www.priyankapanjwani.com/",
   "rachel" : "http://www.rachelhan.ca/",
   "vladan" : "",
   "ziqin" : "http://www.ziqingao.com/",
}
